apiVersion: v1
kind: Service
metadata:
  name: dawn-service
  namespace: dawn-ns
  labels:
    app: dawn
spec:
  type: ClusterIP
  selector:
    app: dawn
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
